My Employees activity
#19
- remove log.d because of FATAL EXCEPTION: main
java.lang.NoSuchMethodError:
com.eusecom.attendance.EmplozeeMvvmActivity.access$lambda$1 by change
retrolambda from classpath 'me.tatarka:gradle-retrolambda:3.2.0' to
classpath 'me.tatarka:gradle-retrolambda:3.3.0'